### ISSUE TITLE
Let uniquetabname also update Outline view

### ISSUE THREAD

**Issue by xopxe** [pkulchenko/ZeroBranePackage#11]
It would be nice if the entries in the Outline window would use the same unique name as the tabs.

**Comment by pkulchenko** [comment]
Jorge, it's possible, but there are some disadvantages to this approach as well. I considered this when implementing the Outline, but decided against it, because it would need to use the labels on the tabs, but those labels also include things like asterisks (`* untitled.lua`) that mark modified documents. I then considered moving the mark for modified documents to the image on the tab, but it didn't work well. I realized that its possible to remove "* " from the name, but it's kind of a hack and so as the result I decided to keep the existing names.

I may still revisit this, but here is the background on this item.

**Comment by xopxe** [comment]
Ok, I see. It would be nice to find some way around this because now I get a bunch of "init.lua" in the Outline, which is otherwise excelent. Handling this case in a smart way would include the libraries in the outline hierarchy, which would be great. It could be the preferred method for navigating biggish  projects, over the file tree or the tabs

**Comment by pkulchenko** [comment]
I agree, it would be nice to have. Let me think about it; maybe I can find a good solution in a couple of days.

**Comment by pkulchenko** [comment]
Jorge, should be fixed now. There are no changes to the plugin, but I made couple of changes to the Outline handling.

**Comment by xopxe** [comment]
It works great! Thank you.

**Comment by xopxe** [comment]
A quick note, perhaps you could extend this naming scheme to the cloned views (now the cloned tab is named "clone: init.lua")

**Comment by pkulchenko** [comment]
@xopxe, should be fixed with the updated `CloneView` plugin (requires post-0.95 ZBS master branch as it uses a new API call).

**Comment by xopxe** [comment]
Effectively, it works.
